### ISSUE TITLE
Error: No path or pathfile specified on the command line!

### ISSUE THREAD

**Issue by VeldMuijz** [cdsama/tortoise-svn-for-vscode#1]
I've tried your extension but I get an error from tortoiseSVN telling me:
No path or pathfile specified on the command line!

This is a blocking issue because none of the commands work from vsCode. The tortoiseSVN application works very good on my pc.

The project i'm using vscode from is on my C:\ drive and I have access to those files.
![image](https://cloud.githubusercontent.com/assets/1394439/17809179/1070ed2e-6615-11e6-89f4-b14ea7716358.png)

**Comment by mksureshkumarmca** [comment]
I am also facing a same issues.. tortoiseSVN is working fine and when i try from VS Code, its show the above error...

**Comment by itzik-h** [comment]
There is a missing semicolon after the path. needs to be `/path:`
See pull request.

**Comment by cdsama** [comment]
ok, guys. I'll check this and reply you ASAP.

**Comment by cdsama** [comment]
Merged [Fix the path to the file - add ":"](https://github.com/cdsama/tortoise-svn-for-vscode/pull/2)
Now the update is available.
