### ISSUE TITLE
Generalize for Linux and possibly OSX

### ISSUE THREAD

**Issue by s-martin** [cdsama/tortoise-svn-for-vscode#4]
It would be great, if this extension could be generalized so it runs also under Linux and possibly OSX.

The capabilites of TortoiseSVN should be available under Linux/OSX, if any SVN package is installed, so the binary to call would be probably `/usr/bin/svn`.

**Comment by GitMensch** [comment]
As this is noted as a change in the release list for 1.1 - shouldn't this issue be closed?

**Comment by GitMensch** [comment]
@s-martin I think it is reasonable to now remove "Tortoise-" from the extension `name`+`displayName` (the repo-name could stay as is, only its description should be adjusted to something like "Using SVN in VS Code (formerly only TortoiseSVN)" with using the same in the `displayName`) as it should work with any SVN client in `PATH`, won't it?
I suggest the simple "SVN for VS Code" as extension name and could do a PR for this. Opinions?
